return {
  "williamboman/mason.nvim",
  event = "LazyFile",
  opts = {
    ensure_installed = {
      "blade-formatter",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "emmet-ls",
      "eslint_d",
      "hadolint",
      "html-lsp",
      "intelephense",
      "phpstan",
      "stylua",
      "luacheck",
      "lua-language-server",
      "pint",
      "tlint",
      -- "sonarlint-language-server",
      -- "pretty-php",
      "psalm",
      "sqlls",
      "sqlfmt",
      "sqlfluff",
      "prettierd",
    },
  },
}
