return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      -- "actionlint",
      -- "ansible-language-server",
      -- "ansible-lint",
      -- "antlers-language-server",
      -- "black",
      "bash-language-server",
      "blade-formatter",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "emmet-ls",
      "eslint_d",
      "hadolint",
      "html-lsp",
      -- "phpactor",
      "intelephense",
      "psalm",
      "phpstan",
      "pretty-php",
      "prettierd",
      "rustywind",
      "shellcheck",
      "shfmt",
      "stylua",
      "selene",
      "tailwindcss-language-server",
    },
  },
}
