return {
  -- {
  --   "nvimtools/none-ls.nvim",
  --   config = function()
  --     local null_ls = require("null-ls")
  --     local lspconfig = require("lspconfig")
  --
  --     -- Setup null-ls
  --     null_ls.config({
  --       sources = {
  --         -- PHP completion source for Blade files
  --         null_ls.builtins.completion.with({
  --           method = null_ls.methods.CODE_ACTION,
  --           filetypes = { "blade.php" },  -- Apply to Blade files
  --           generator = {
  --             fn = function(params)
  --               -- Only trigger completion inside {{ ... }} tags
  --               local line = params.content[params.row]
  --               local start_index, end_index = string.find(line, "{{.*}}", 1, true)
  --               if start_index and end_index and params.col >= start_index and params.col <= end_index then
  --                 return {
  --                   {
  --                     title = "Intelephense",
  --                     action = {
  --                       command = "intelephense.doComplete",
  --                       arguments = {
  --                         params.context.cursor_pos,
  --                         vim.api.nvim_get_current_buf(),
  --                       },
  --                     },
  --                   },
  --                 }
  --               end
  --               return {}
  --             end,
  --           },
  --         }),
  --       },
  --     })
  --
  --     -- Configure Intelephense with null-ls
  --     lspconfig.intelephense.setup({
  --       on_attach = function(client, bufnr)
  --         null_ls.setup(client)
  --       end,
  --     })
  --   end,
  -- },
}
